<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>SF9 — {{ $student->name }}</title>
    <style>
        body { font-family: Arial, sans-serif; font-size: 12px; color: #222; margin: 24px; }
        h1, h2 { text-align: center; margin: 0; }
        .school-header { text-align: center; margin-bottom: 20px; border-bottom: 2px solid #0a4d68; padding-bottom: 12px; }
        .meta { width: 100%; margin: 16px 0; }
        .meta td { padding: 4px 8px; }
        table.grades { width: 100%; border-collapse: collapse; margin-top: 16px; }
        table.grades th, table.grades td { border: 1px solid #ccc; padding: 6px 8px; text-align: center; }
        table.grades th { background: #0a4d68; color: #fff; }
        .descriptor { font-weight: bold; }
        .print-btn { margin: 16px 0; padding: 10px 20px; background: #0a4d68; color: #fff; border: none; cursor: pointer; }
        @media print { .print-btn { display: none; } }
        .form-title { background: #e8f4fc; padding: 8px; font-weight: bold; text-align: center; }
    </style>
</head>
<body>
    <button class="print-btn" onclick="window.print()">Print SF9</button>

    <div class="school-header">
        <h2>{{ $student->section->class->school->name ?? 'School' }}</h2>
        <p>{{ $student->section->class->school->about ?? '' }}</p>
        <div class="form-title">SF9 — Learner's Progress Report Card</div>
        <p>School Year: <strong>{{ $schoolYear->name }}</strong></p>
    </div>

    <table class="meta">
        <tr>
            <td><strong>Learner Name:</strong> {{ $student->name }}</td>
            <td><strong>LRN / ID:</strong> {{ $student->student_code }}</td>
        </tr>
        <tr>
            <td><strong>Grade Level:</strong> {{ $student->section->class->class_number ?? '' }}</td>
            <td><strong>Section:</strong> {{ $student->section->section_number ?? '' }}</td>
        </tr>
    </table>

    @foreach($grades as $courseId => $courseGrades)
        @php $course = $courses->get($courseId); @endphp
        <h3 style="margin-top:24px;">{{ $course->course_name ?? 'Subject' }}</h3>
        <table class="grades">
            <thead>
                <tr>
                    <th>Quarter</th>
                    <th>WW %</th>
                    <th>PT %</th>
                    <th>QA %</th>
                    <th>Initial Grade</th>
                    <th>Final Grade</th>
                    <th>Descriptor</th>
                </tr>
            </thead>
            <tbody>
                @foreach($courseGrades->sortBy(function($g) { return $g->quarter->quarter_number; }) as $g)
                    <tr>
                        <td>{{ $g->quarter->name }}</td>
                        <td>{{ $g->written_work_percent }}</td>
                        <td>{{ $g->performance_task_percent }}</td>
                        <td>{{ $g->quarterly_assessment_percent }}</td>
                        <td>{{ $g->initial_grade }}</td>
                        <td>{{ $g->transmuted_grade }}</td>
                        <td class="descriptor">{{ $g->descriptor }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @endforeach

    @if($grades->isEmpty())
        <p>No quarterly grades recorded for this school year.</p>
    @endif

    <p style="margin-top:40px; text-align:center; font-size:10px; color:#666;">
        Generated by SmartCampus K–12 · DepEd-aligned quarterly grading
    </p>
</body>
</html>
